// <auto-generated />
namespace PropertyWebManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class start20151104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start20151104));
        
        string IMigrationMetadata.Id
        {
            get { return "201511042222023_start20151104"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
