//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesNieruchomosci : DbContext
    {
        public EntitiesNieruchomosci()
            : base("name=EntitiesNieruchomosci")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Nieruchomosc> Nieruchomosc { get; set; }
        public DbSet<NieruchomoscPhoto> NieruchomoscPhoto { get; set; }
        public DbSet<RodzajNieruchomosci> RodzajNieruchomosci { get; set; }
        public DbSet<TypTransakcji> TypTransakcji { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
