//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class NieruchomoscPhoto
    {
        public int NieruchomoscID { get; set; }
        public int ImageID { get; set; }
        public int ImageSize { get; set; }
        [Display(Name = "Nazwa pliku")]
        public string FileName { get; set; }

        public byte[] ImageData { get; set; }
        [Required(ErrorMessage = "Please select file")]
        public HttpPostedFileBase File { get; set; }
        public byte[] ImageData1 { get; set; }
        public virtual Nieruchomosc Nieruchomosc { get; set; }
    }
}

