//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RodzajNieruchomosci
    {
        public RodzajNieruchomosci()
        {
            this.Nieruchomosc = new HashSet<Nieruchomosc>();
        }
    
        public int RodzajNieruchomosciID { get; set; }
      [Display(Name = "Rodzaj nieruchomoœci")]
        public string RodzajNieruchomosciRodzaj { get; set; }
    
        public virtual ICollection<Nieruchomosc> Nieruchomosc { get; set; }
    }
}
