//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TypTransakcji
    {
        public TypTransakcji()
        {
            this.Nieruchomosc = new HashSet<Nieruchomosc>();
        }
    
        public int TypTransakcjiID { get; set; }
        [Display(Name = "Typ transakcji")]
        public string Typ { get; set; }
    
        public virtual ICollection<Nieruchomosc> Nieruchomosc { get; set; }
    }
}
