//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nieruchomosci.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Nieruchomosc = new HashSet<Nieruchomosc>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        [Display(Name = "Nazwa u¿ytkownika")]
        public string UserName { get; set; }
    
        public virtual ICollection<Nieruchomosc> Nieruchomosc { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
